"""TeamInvitation model - tracks pending team invitations generated by admin"""
from sqlalchemy import Column, String, DateTime, ForeignKey, Enum as SQLEnum
from sqlalchemy.orm import relationship
from datetime import datetime
import uuid

from app.database import Base
from app.models.user import UserRole


class TeamInvitation(Base):
    __tablename__ = "team_invitations"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    team_id = Column(String(36), ForeignKey("teams.id", ondelete="CASCADE"), nullable=False)
    email = Column(String(255), nullable=True)  # optional pre-fill; None = open invite
    role = Column(SQLEnum(UserRole, values_callable=lambda x: [e.value for e in x]), default=UserRole.DEVELOPER, nullable=False)
    token = Column(String(128), unique=True, nullable=False, index=True)
    invited_by_id = Column(String(36), ForeignKey("users.id", ondelete="SET NULL"), nullable=True)
    expires_at = Column(DateTime, nullable=False)
    used_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    team = relationship("Team")
    invited_by = relationship("User", foreign_keys=[invited_by_id])
